name: WorldWalk
description: 번역 앱
version: 1.0.2+3

environment:
  sdk: ">=2.18.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.6
  
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  carousel_slider: ^4.2.1
  firebase_storage: ^11.2.3
  flutter_screenutil: ^5.8.4
  flutter_local_notifications: ^14.1.1
  permission_handler: ^10.3.0
  url_launcher: ^6.1.11
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  image_picker: ^0.8.9
  cloud_firestore: ^4.8.1
  package_info_plus: ^4.0.2
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3
  html_unescape: ^2.0.0
  firebase_messaging: ^14.6.5
  flutter_tts: ^3.7.0
  speech_to_text: ^6.3.0
  google_translate: ^0.0.6
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Thin.ttf
          weight: 100
        - asset: assets/font/Inter-Light.ttf
          weight: 300
        - asset: assets/font/Inter-Regular.ttf
          weight: 400
        - asset: assets/font/Inter-Medium.ttf
          weight: 500
        - asset: assets/font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/font/Inter-Bold.ttf
          weight: 700
        - asset: assets/font/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Inter-Black.ttf
          weight: 900
    - family: Gothic
      fonts:
        - asset: assets/font/GothicA1-Thin.ttf
          weight: 100
        - asset: assets/font/GothicA1-Light.ttf
          weight: 300
        - asset: assets/font/GothicA1-Regular.ttf
          weight: 400
        - asset: assets/font/GothicA1-Medium.ttf
          weight: 500
        - asset: assets/font/GothicA1-SemiBold.ttf
          weight: 600
        - asset: assets/font/GothicA1-Bold.ttf
          weight: 700
        - asset: assets/font/GothicA1-ExtraBold.ttf
          weight: 800
        - asset: assets/font/GothicA1-Black.ttf
          weight: 900
    - family: Audiowide
      fonts:
        - asset: assets/font/Audiowide-Regular.ttf
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/Pretendard-Bold.ttf
    - family: NotoSans
      fonts:
        - asset: assets/font/NotoSans-Regular.ttf
          
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
