// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBB1ueL6j3Oorh1B5rrWK3YE79j87BnKAY",
      appId: "1:195128754445:android:f6d6489577ee38a3a87044",
      messagingSenderId: '195128754445',
      projectId: "worldwalk-ba6e5",
      storageBucket: "worldwalk-ba6e5.appspot.com");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyBMnEacUc9X8c4b_nQA57Dcfe4qE-VEJ3E",
      appId: '1:195128754445:ios:d953bf23d06a7153a87044',
      messagingSenderId: '195128754445',
      projectId: "worldwalk-ba6e5",
      storageBucket: "worldwalk-ba6e5.appspot.com",
      iosClientId: '',
      iosBundleId: 'com.world.walk',
      androidClientId: "");
}
